### PR TITLE
[Merged by Bors] - ci: add new e2e system (IN-707)

### PR DESCRIPTION
**Pull request by Xavientois**
**Fixes or implements IN-707**

### Brief description. What is this change?

- Adds new e2e system
- Parameterize orb version

### CODE REVIEW

**Comment by Xavientois** [comment]
bors try

**Comment by Xavientois** [comment]
bors try

**Review by xavidop — APPROVED** [review]

**Comment by Xavientois** [comment]
bors merge

**Comment by Xavientois** [comment]
bors merge

**Pull request closed without merging**
