### PR TITLE
feat: integrate e2e env pooling for smoke test (IN-947)

### PR DESCRIPTION
**Pull request by junydania**
**Fixes or implements IN-947**

### Brief description. What is this change?

Integrate e2e pooling for smoke tests

### Related PRs

- https://github.com/voiceflow/XXXXXXXXX/pull/123

### Checklist

- [ ] Breaking changes have been communicated, including:
    - New required environment variables
    - Renaming of interfaces (API routes, request/response interface, etc)
- [ ] New environment variables have [been deployed](https://www.notion.so/voiceflow/Add-Environment-Variables-be1b0136479f45f1adece7995a7adbfb)
- [ ] Appropriate tests have been written
    - Bug fixes are accompanied by an updated or new test
    - New features are accompanied by a new test

### CODE REVIEW

**Comment by junydania** [comment]
bors try

**Comment by junydania** [comment]
bors try

**Comment by junydania** [comment]
bors try

**Comment by junydania** [comment]
bors try

**Comment by junydania** [comment]
bors try

**Review by xavidop — APPROVED** [review]

**Pull request merged**
