### PR TITLE
[Merged by Bors] - ci: use new ci job for checking service runs in e2e environment

### PR DESCRIPTION
**Pull request by effervescentia**

### CODE REVIEW

**Comment by effervescentia** [comment]
bors try

**Comment by effervescentia** [comment]
bors try-

**Comment by effervescentia** [comment]
bors try

**Comment by effervescentia** [comment]
bors try

**Comment by effervescentia** [comment]
bors try

**Comment by effervescentia** [comment]
bors try

**Comment by effervescentia** [comment]
bors try

**Review by DecathectZero — APPROVED** [review]

**Pull request closed without merging**
